port: 8083
applicationID: aggregationSvc
serverAddressing: localhost:8091
tm:
  commitRetryCount: 5
  rollbackRetryCount: 5
clientParameters:
  time: 10s
  timeout: 1s
  permitWithoutStream: true
log:
  logPath: /Users/scottlewis/dksl/temp/seata-samples/http/aggregation_svc/aggregation.log
  logLevel: info